In [4]:
!nvidia-smi

Mon Aug 21 05:28:54 2023       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 536.99                 Driver Version: 536.99       CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                     TCC/WDDM  | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce GTX 1050 Ti   WDDM  | 00000000:01:00.0  On |                  N/A |
| 47%   46C    P0              N/A /  75W |   1083MiB /  4096MiB |      1%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [5]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
print(torch.cuda.is_available())
print(torch.cuda.device_count())
print(torch.cuda.current_device())
print(torch.cuda.device(0))
print(torch.cuda.get_device_name(0))
print(torch.__version__)

True
1
0
NVIDIA GeForce GTX 1050 Ti
2.0.1+cu118


In [7]:
#A torch.Tensor is a multi-dimensional matrix containing elements of a single data type
#In PyTorch,tensors encode the inputs and outputs of a model, as well as the model’s parameters.
#Tensors are similar to NumPy’s ndarrays, except that tensors can run on GPUs or other hardware accelerators
scalar = torch.tensor(7) #tensor data-type
scalar

tensor(7)

In [8]:
#A scalar is a single number and in tensor-speak it's a zero dimension tensor.
scalar.ndim

0

In [9]:
# Get the Python int/number within a tensor (only works with one-element tensors)
scalar.item()

7

In [10]:
#A vector is a single dimension tensor but can contain many numbers, 1 square bracket [] pairing
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [11]:
vector.ndim

1

In [12]:
#The shape tells you how the elements inside them are arranged
vector.shape #2x1 elements total of 2 elements
#two elements was placed inside the square brackets ([7, 7]).

torch.Size([2])

In [22]:
# Matrix (list of list) 2 square bracket [] pairing
MATRIX = torch.tensor([[7, 8, 0], 
                       [9, 10, 11],
                       [1, 2, 3]])
MATRIX 

tensor([[ 7,  8,  0],
        [ 9, 10, 11],
        [ 1,  2,  3]])

In [23]:
# Check number of dimensions
MATRIX.ndim

2

In [24]:
MATRIX[1]

tensor([ 9, 10, 11])

In [20]:
MATRIX.shape #3 x 3 matrix 3 elements

torch.Size([3, 3])

In [42]:
# Tensor 3 square bracket [] pairing
TENSOR = torch.tensor([[[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]]])
TENSOR

tensor([[[[1, 2, 3],
          [3, 6, 9],
          [2, 4, 5]]]])

In [43]:
# Check number of dimensions for TENSOR
TENSOR.ndim

4

In [44]:
TENSOR.shape

torch.Size([1, 1, 3, 3])

<div>
<img src="img/00-pytorch-different-tensor-dimensions.png" width="700"/>
</div>

In [45]:
TENSOR[0]

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

> **Note:** You might've noticed me using lowercase letters for `scalar` and `vector` and uppercase letters for `MATRIX` and `TENSOR`. This was on purpose. In practice, you'll often see scalars and vectors denoted as lowercase letters such as `y` or `a`. And matrices and tensors denoted as uppercase letters such as `X` or `W`.
>
> You also might notice the names martrix and tensor used interchangably. This is common. Since in PyTorch you're often dealing with `torch.Tensor`s (hence the tensor name), however, the shape and dimensions of what's inside will dictate what it actually is.

Let's summarise.

| Name | What is it? | Number of dimensions | Lower or upper (usually/example) |
| ----- | ----- | ----- | ----- |
| **scalar** | a single number | 0 | Lower (`a`) | 
| **vector** | a number with direction (e.g. wind speed with direction) but can also have many other numbers | 1 | Lower (`y`) |
| **matrix** | a 2-dimensional array of numbers | 2 | Upper (`Q`) |
| **tensor** | an n-dimensional array of numbers | can be any number, a 0-dimension tensor is a scalar, a 1-dimension tensor is a vector | Upper (`X`) | 

![scalar vector matrix tensor and what they look like](https://raw.githubusercontent.com/mrdbourke/pytorch-deep-learning/main/images/00-scalar-vector-matrix-tensor.png)

In [47]:
# Create a random tensor of size (1, 3, 4)
random_tensor = torch.rand(size=(1, 3, 4))
random_tensor, random_tensor.dtype

(tensor([[[0.4802, 0.5236, 0.0322, 0.8196],
          [0.8036, 0.7131, 0.5593, 0.1586],
          [0.3646, 0.6018, 0.9454, 0.1228]]]),
 torch.float32)