In [1]:
!nvidia-smi

Wed Aug 23 23:53:43 2023       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 537.13                 Driver Version: 537.13       CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                     TCC/WDDM  | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce GTX 1050 Ti   WDDM  | 00000000:01:00.0  On |                  N/A |
| 46%   44C    P0              N/A /  75W |    877MiB /  4096MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [2]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
print(torch.cuda.is_available())
print(torch.cuda.device_count())
print(torch.cuda.current_device())
print(torch.cuda.device(0))
print(torch.cuda.get_device_name(0))
print(torch.__version__)

True
1
0
NVIDIA GeForce GTX 1050 Ti
2.0.1+cu118


In [3]:
#A torch.Tensor is a multi-dimensional matrix containing elements of a single data type
#In PyTorch,tensors encode the inputs and outputs of a model, as well as the model’s parameters.
#Tensors are similar to NumPy’s ndarrays, except that tensors can run on GPUs or other hardware accelerators
scalar = torch.tensor(7) #tensor data-type
scalar

tensor(7)

In [4]:
#A scalar is a single number and in tensor-speak it's a zero dimension tensor.
scalar.ndim

0

In [5]:
# Get the Python int/number within a tensor (only works with one-element tensors)
scalar.item()

7

In [6]:
#A vector is a single dimension tensor but can contain many numbers, 1 square bracket [] pairing
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
#The shape tells you how the elements inside them are arranged
vector.shape #2x1 elements total of 2 elements
#two elements was placed inside the square brackets ([7, 7]).

torch.Size([2])

In [9]:
# Matrix (list of list) 2 square bracket [] pairing
MATRIX = torch.tensor([[7, 8, 0], 
                       [9, 10, 11],
                       [1, 2, 3]])
MATRIX 

tensor([[ 7,  8,  0],
        [ 9, 10, 11],
        [ 1,  2,  3]])

In [10]:
# Check number of dimensions
MATRIX.ndim

2

In [11]:
MATRIX[1]

tensor([ 9, 10, 11])

In [12]:
MATRIX.shape #3 x 3 matrix 3 elements

torch.Size([3, 3])

In [13]:
# Tensor 3 square bracket [] pairing
TENSOR = torch.tensor([[[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]]])
TENSOR

tensor([[[[1, 2, 3],
          [3, 6, 9],
          [2, 4, 5]]]])

In [14]:
# Check number of dimensions for TENSOR
TENSOR.ndim

4

In [15]:
TENSOR.shape

torch.Size([1, 1, 3, 3])

<div>
<img src="img/00-pytorch-different-tensor-dimensions.png" width="700"/>
</div>

In [16]:
TENSOR[0]

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

> **Note:** You might've noticed me using lowercase letters for `scalar` and `vector` and uppercase letters for `MATRIX` and `TENSOR`. This was on purpose. In practice, you'll often see scalars and vectors denoted as lowercase letters such as `y` or `a`. And matrices and tensors denoted as uppercase letters such as `X` or `W`.
>
> You also might notice the names martrix and tensor used interchangably. This is common. Since in PyTorch you're often dealing with `torch.Tensor`s (hence the tensor name), however, the shape and dimensions of what's inside will dictate what it actually is.

Let's summarise.

| Name | What is it? | Number of dimensions | Lower or upper (usually/example) |
| ----- | ----- | ----- | ----- |
| **scalar** | a single number | 0 | Lower (`a`) | 
| **vector** | a number with direction (e.g. wind speed with direction) but can also have many other numbers | 1 | Lower (`y`) |
| **matrix** | a 2-dimensional array of numbers | 2 | Upper (`Q`) |
| **tensor** | an n-dimensional array of numbers | can be any number, a 0-dimension tensor is a scalar, a 1-dimension tensor is a vector | Upper (`X`) | 

![scalar vector matrix tensor and what they look like](https://raw.githubusercontent.com/mrdbourke/pytorch-deep-learning/main/images/00-scalar-vector-matrix-tensor.png)

In [17]:
# Create a random tensor of size (1, 3, 4)
random_tensor = torch.rand(size=(1, 3, 4))
random_tensor, random_tensor.dtype, random_tensor.ndim

(tensor([[[0.7788, 0.1186, 0.9794, 0.0850],
          [0.5711, 0.9886, 0.4903, 0.1751],
          [0.3547, 0.7668, 0.8531, 0.0502]]]),
 torch.float32,
 3)

In [18]:
#fill tensors with zeros or ones.
#masking some of the values in one tensor with zeros to let a model know not to learn them
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [19]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

In [20]:
# Use torch.arange(), torch.range() is deprecated 
zero_to_ten_deprecated = torch.range(0, 10) # Note: this may return an error in the future
zero_to_ten_deprecated 

C:\Users\aliah\AppData\Local\Temp\ipykernel_29452\1550859357.py:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  zero_to_ten_deprecated = torch.range(0, 10) # Note: this may return an error in the future


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [21]:
torch.arange(0, 10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
# Create a range of values 0 to 10
zero_to_nine= torch.arange(start=0, end=10, step=1)
zero_to_nine

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
# Create a tensor of zeros similar to another tensor
ten_zeros = torch.zeros_like(input=zero_to_nine)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

There are many different [tensor datatypes available in PyTorch](https://pytorch.org/docs/stable/tensors.html#data-types).
Some are specific for CPU and some are better for GPU.
Generally if you see `torch.cuda` anywhere, the tensor is being used for GPU (since Nvidia GPUs use a computing toolkit called CUDA).
The most common type (and generally the default) is `torch.float32` or `torch.float`.
But there's also 16-bit floating point (`torch.float16` or `torch.half`) and 64-bit floating point (`torch.float64` or `torch.double`).
And to confuse things even more there's also 8-bit, 16-bit, 32-bit and 64-bit integers. Plus more!
Getting to know which is which can take some time.
The reason for all of these is to do with **precision in computing**. Precision is the amount of detail used to describe a number. The higher the precision value (8, 16, 32), the more detail and hence data used to express a number. Lower precision datatypes are generally faster to compute on but sacrifice some performance on evaluation metrics like accuracy (faster to compute but less accurate).


In [24]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded 

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [25]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16,
                               device="cpu") # torch.half would also work

float_16_tensor.dtype,float_16_tensor.device

(torch.float16, device(type='cpu'))

In [26]:
float_32_cuda_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float32,
                               device="cuda",
                               requires_grad=True) # torch.half would also work
float_32_cuda_tensor.shape, float_32_cuda_tensor.dtype, float_32_cuda_tensor.device

(torch.Size([3]), torch.float32, device(type='cuda', index=0))

In [27]:
float_16_tensor * float_32_tensor #some tensors with not the right data type may show error (different datatype)

tensor([ 9., 36., 81.])

In [28]:
int_32_tensor= torch.tensor([3, 6, 9],
                               dtype=torch.int32)
int_32_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [29]:
#Getting information from tensors
# Create a tensor
some_tensor = torch.rand(3, 4)

# Find out details about it
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}") # will default to CPU

tensor([[0.7831, 0.8269, 0.2213, 0.3689],
        [0.5691, 0.8007, 0.1616, 0.5327],
        [0.4942, 0.8772, 0.3171, 0.2491]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


## Manipulating tensors (tensor operations)

In deep learning, data (images, text, video, audio, protein structures, etc) gets represented as tensors.

A model learns by investigating those tensors and performing a series of operations (could be 1,000,000s+) on tensors to create a representation of the patterns in the input data.

These operations are often a wonderful dance between:
* Addition
* Substraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [30]:
# Create a tensor of values and add a number to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [31]:
# Multiply it by 10
tensor * 10

tensor([10, 20, 30])

In [32]:
tensor

tensor([1, 2, 3])

In [33]:
tensor = tensor * 10 + 1
tensor 

tensor([11, 21, 31])

In [34]:
tensor = tensor - 100
tensor 

tensor([-89, -79, -69])

PyTorch also has a bunch of built-in functions like [`torch.mul()`](https://pytorch.org/docs/stable/generated/torch.mul.html#torch.mul) (short for multiplication) and [`torch.add()`](https://pytorch.org/docs/stable/generated/torch.add.html) to perform basic operations. 

In [35]:
# Can also use torch functions
torch = torch.multiply(tensor, 10)
torch

tensor([-890, -790, -690])

In [37]:
torch = torch.add(1000) #only one argument for add() func
torch

tensor([110, 210, 310])